language: python

dist: trusty
sudo: false

cache:
  pip: true

env:
  global:
    - NOSE=
    - PYTEST='pytest!=3.3.0,>=3.2.0'
    - PYTEST_COV=pytest-cov
    - PYTEST_PEP8=
    - NPROC=2
    - RUN_PEP8=
    - PYTEST_ARGS="-rawR --maxfail=50 --timeout=300 --durations=25 --cov-report= --cov=lib -n $NPROC"
    - PYTHON_ARGS=

matrix:
  include:
    - python: 3.5
      # pytest-cov>=2.3.1 due to https://github.com/pytest-dev/pytest-cov/issues/124.
      env:
        - CYCLER=cycler==0.10
        - NOSE=nose
        - PYTEST=pytest==3.1.0
        - PYTEST_COV=pytest-cov==2.3.1
    - python: 3.5
      env: PYTHON_ARGS=-OO
    - python: 3.6
      env: DELETE_FONT_CACHE=1 PYTEST_PEP8=pytest-pep8 RUN_PEP8=--pep8
    - python: "nightly"
      env: PRE=--pre
    - os: osx
      language: generic  # https://github.com/travis-ci/travis-ci/issues/2312
      only: master
      cache:
        # As for now travis caches only "$HOME/.cache/pip"
        # https://docs.travis-ci.com/user/caching/#pip-cache
        pip: false
        directories:
          - $HOME/Library/Caches/pip
  allow_failures:
    - python: "nightly"

before_install:
  - |
    if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
      # test with non-ascii in path
      mkdir /tmp/λ
      export PATH=$PATH:/tmp/λ
    else
      ci/travis/silence brew update
      brew upgrade python
      hash -r
      which python
      python --version
      # We could install ghostscript and inkscape here to test svg and pdf
      # but this makes the test time really long.
      # brew install ghostscript inkscape
      export PATH=/usr/local/opt/python/libexec/bin:$PATH
    fi

install:
  - |
    git describe
    # Upgrade pip and setuptools and wheel to get as clean an install as possible.
    python -mpip install --upgrade pip setuptools wheel
  - |
    # Install dependencies from PyPI.
    python -mpip install --upgrade $PRE \
        codecov \
        coverage \
        $NOSE \
        codecov \
        coverage \
    python -mpip install $PRE \
        $PYTEST \
        $PYTEST_COV \
        pytest-faulthandler \
        $PYTEST_PEP8 \
        pytest-rerunfailures \
        pytest-timeout \
        pytest-xdist
before_script:
  - |
    if [[ $TRAVIS_OS_NAME != 'osx' ]]; then
      export DISPLAY=:99.0
      sh -e /etc/init.d/xvfb start
    fi
script: test/test_script.sh

after_failure:
  - |
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == 'lidio601/docker-dns-rest' ]]; then
      echo 'See logs'
    fi
after_success:
  - codecov -e TRAVIS_PYTHON_VERSION
